In [2]:
import pandas as pd
import numpy as np
import csv
import ast

In [3]:
pd.options.display.max_columns = False

In [4]:
chunk = pd.read_csv('../../data/raw.csv', engine='c',sep=',', encoding='utf-8', on_bad_lines='skip', chunksize=11000)

In [5]:
df = chunk.get_chunk(11000)

In [6]:
selected_cols = ['title', 'createdAt',
       'cities', 'price', 'smallDescription', 'store.name',
]

In [7]:
df = df[selected_cols]

In [8]:
df['createdAt'] = pd.to_datetime(df['createdAt'])
df.price = pd.to_numeric(df.price, downcast='integer')

In [9]:
df.dtypes

title                            object
createdAt           datetime64[ns, UTC]
cities                           object
price                           float64
smallDescription                 object
store.name                       object
dtype: object

In [10]:
city = pd.json_normalize(df.cities.apply(ast.literal_eval).explode()).drop(columns=['id', 'slug', '__typename', 'region.id', 'region.slug', 'region.__typename' ]).rename(columns={'name':'Town', 'region.name':'Wilaya'})
area = pd.json_normalize(df.smallDescription.apply(ast.literal_eval).explode()).drop(columns= ['__typename']).rename(columns={'valueText': 'Area'})

In [11]:
def to_integer(s:str) -> str:
    string = ''.join(c for c in s if c.isdigit())
    return eval(string)

In [12]:
area.Area.apply(to_integer)

SyntaxError: invalid syntax (<string>, line 0)

In [207]:
df = pd.concat([df, city, area], axis=1)

In [208]:
df = df.drop(columns=['cities', 'smallDescription'])

KeyError: "['cities' 'smallDescription'] not found in axis"

In [209]:
df = df.rename(columns ={'title': 'Title', 'createdAt': 'Date', 'store.name': 'Store', 'price': 'Price'})

In [210]:
df.head(20)

                                             Title  ... Area
0       Vente Appartement F4 Alger Bordj el kiffan  ...  NaN
1               Vente Appartement F2 Alger Cheraga  ...  NaN
2            Location Appartement F3 Annaba Annaba  ...  NaN
3            Vente Appartement F4 Alger Mohammadia  ...  NaN
4        Vente Appartement F3 Alger Bordj el bahri  ...  NaN
5            Location Appartement F4 Alger Cheraga  ...  NaN
6   Location vacances Villa Tipaza Hadjeret ennous  ...  NaN
7         Location Appartement F3 Alger Mohammadia  ...  NaN
8                     Location Local Alger Cheraga  ...  NaN
9       Location vacances Appartement F3 Oran Oran  ...  NaN
10        Location Appartement F3 Alger Mohammadia  ...  NaN
11             Vente Appartement F3 Alger El marsa  ...  NaN
12                       Vente Villa Oran Es senia  ...  NaN
13  Location vacances Appartement F2 Béjaïa Bejaia  ...  NaN
14       Location Appartement F3 Alger El mouradia  ...  NaN
15          Vente Appartement Alger Bordj el bahri  ...  NaN
16           Vente Appartement F2 Alger Mohammadia  ...  NaN
17             Vente Appartement F3 Alger Ain taya  ...  NaN
18       Vente Appartement F2 Alger Bordj el bahri  ...  NaN
19                  Vente Appartement Alger Saoula  ...  NaN

[20 rows x 13 columns]